import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from "react";
import * as SelectPrimitive from "@radix-ui/react-select";
const cn = (...classes) => classes.filter(Boolean).join(" ");
const Select = SelectPrimitive.Root;
const Chevron = () => (_jsx("svg", { className: "ml-2 h-3 w-3 text-muted-foreground", viewBox: "0 0 8 6", fill: "none", children: _jsx("path", { d: "M1 1.5L4 4.5L7 1.5", stroke: "currentColor", strokeWidth: "1.2", strokeLinecap: "round" }) }));
const Check = () => (_jsx("svg", { className: "h-3 w-3 text-accent", viewBox: "0 0 16 12", fill: "none", children: _jsx("path", { d: "M1 6.5L5.5 11L15 1", stroke: "currentColor", strokeWidth: "1.6", strokeLinecap: "round", strokeLinejoin: "round" }) }));
const SelectTrigger = React.forwardRef(({ className, children, ...props }, ref) => (_jsxs(SelectPrimitive.Trigger, { ref: ref, className: cn("inline-flex h-11 w-full items-center justify-between rounded-2xl border border-white/10 bg-surface-strong/70 px-4 py-2 text-sm text-foreground shadow-[0_20px_40px_-30px_rgba(56,189,248,0.45)] transition", "focus:outline-none focus:ring-2 focus:ring-accent/40", "disabled:cursor-not-allowed disabled:opacity-50", className), ...props, children: [children, _jsx(SelectPrimitive.Icon, { children: _jsx(Chevron, {}) })] })));
SelectTrigger.displayName = SelectPrimitive.Trigger.displayName;
const SelectContent = React.forwardRef(({ className, children, position = "popper", ...props }, ref) => (_jsx(SelectPrimitive.Portal, { children: _jsx(SelectPrimitive.Content, { ref: ref, position: position, sideOffset: 8, collisionPadding: 8, className: cn("z-50 min-w-[var(--radix-select-trigger-width)] overflow-hidden rounded-2xl border border-white/10", "bg-surface-strong/95 text-foreground shadow-[0_20px_40px_-28px_rgba(56,189,248,0.55)] backdrop-blur-xl", "data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0", className), ...props, children: _jsx(SelectPrimitive.Viewport, { className: "max-h-[50vh] overflow-auto p-2", children: children }) }) })));
SelectContent.displayName = SelectPrimitive.Content.displayName;
const SelectItem = React.forwardRef(({ className, children, ...props }, ref) => (_jsxs(SelectPrimitive.Item, { ref: ref, className: cn("relative flex w-full cursor-default select-none items-center justify-between rounded-xl px-3 py-2 text-sm text-muted-foreground transition", "focus:bg-accent/10 focus:text-foreground", "data-[disabled]:pointer-events-none data-[disabled]:opacity-40", className), ...props, children: [_jsx(SelectPrimitive.ItemText, { children: children }), _jsx(SelectPrimitive.ItemIndicator, { className: "absolute right-3 flex items-center justify-center", children: _jsx(Check, {}) })] })));
SelectItem.displayName = SelectPrimitive.Item.displayName;
const SelectValue = SelectPrimitive.Value;
export { Select, SelectContent, SelectItem, SelectTrigger, SelectValue };
