ALTER TYPE "pou_failure_reason" ADD VALUE IF NOT EXISTS 'DB_WRITE_FAILED';
ALTER TYPE "pou_failure_reason" ADD VALUE IF NOT EXISTS 'OUTPUT_UNAVAILABLE';
ALTER TYPE "pou_failure_reason" ADD VALUE IF NOT EXISTS 'HASH_ERROR';
ALTER TYPE "pou_failure_reason" ADD VALUE IF NOT EXISTS 'ATTESTATION_FAILED';
