import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/policy/TenantPolicyStore.ts",
    "src/queue/*.ts",
    "src/llm/*.ts",
    "src/logging/*.ts",
    "src/actions/*.ts",
    "src/actions/agents/*.ts",
    "src/actions/registry/*.ts",
    "src/actions/reporting/*.ts",
    "src/services/*.ts",
    "src/taxonomy/*.ts",
  ],
  outDir: "dist",
  format: ["esm"],
  target: "node20",
  sourcemap: true,
  clean: false,
  splitting: false,
  bundle: true,
  shims: false,
  dts: false,
  external: [
    "fs",
    "path",
    "os",
    "@prisma/client",
    "ioredis",
    "bullmq",
    "dotenv",
    "dotenv/config",
    "pino",
    "zod",
  ],
});
