openapi: "3.1.0"
info:
  title: EIAH Public API
  version: 0.1.0
tags:
  - name: runs
    description: Observability endpoints
  - name: billing
    description: Cost control endpoints
  - name: agents
    description: Agent catalog
servers:
  - url: https://api.eiah.local
paths:
  /runs:
    get:
      operationId: listRuns
      summary: Lista runs com filtros e paginação
      parameters:
        - in: query
          name: agent
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: string
            enum:
              - success
              - error
              - blocked
        - in: query
          name: projectId
          schema:
            type: string
        - in: query
          name: from
          schema:
            type: string
            format: date-time
        - in: query
          name: to
          schema:
            type: string
            format: date-time
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 50
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Run'
                  total:
                    type: integer
  /runs/{id}:
    get:
      operationId: getRun
      summary: Detalhe de um run
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Run'
  /billing/estimate:
    post:
      operationId: estimateCost
      summary: Estima custo antes da execução
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agent:
                  type: string
                inputBytes:
                  type: integer
                tools:
                  type: array
                  items:
                    type: string
                projectId:
                  type: string
              required:
                - agent
                - inputBytes
                - projectId
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  data:
                    type: object
                    properties:
                      estimateCents:
                        type: integer
                      currency:
                        type: string
                        default: BRL
  /billing/charge:
    post:
      operationId: chargeUsage
      summary: Registra débito de um run concluído
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                runId:
                  type: string
                projectId:
                  type: string
                costCents:
                  type: integer
              required:
                - runId
                - projectId
                - costCents
      responses:
        "200":
          description: OK
  /plans/quotas:
    get:
      operationId: getPlanQuota
      summary: Consulta limites/consumo do projeto
      parameters:
        - in: query
          name: projectId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  data:
                    type: object
                    properties:
                      softLimitCents:
                        type: integer
                      hardLimitCents:
                        type: integer
                      monthUsageCents:
                        type: integer
                      percent:
                        type: number
  /agents:
    get:
      operationId: listAgents
      summary: Lista agentes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Agent'
    post:
      operationId: createAgent
      summary: Cria agente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Agent'
      responses:
        "201":
          description: Created
  /agents/{id}:
    get:
      operationId: getAgent
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
    put:
      operationId: updateAgent
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Agent'
      responses:
        "200":
          description: OK
    delete:
      operationId: deleteAgent
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
  /webhooks/billing:
    post:
      operationId: webhookBilling
      summary: Recebe eventos do gateway de pagamento
      responses:
        "200":
          description: OK
components:
  schemas:
    Run:
      type: object
      properties:
        id:
          type: string
        projectId:
          type: string
        agent:
          type: string
        status:
          type: string
          enum:
            - success
            - error
            - blocked
        request:
          type: object
        response:
          type: object
        costCents:
          type: integer
        startedAt:
          type: string
          format: date-time
        finishedAt:
          type: string
          format: date-time
        meta:
          type: object
          properties:
            traceId:
              type: string
            tookMs:
              type: number
    Agent:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        basePrompt:
          type: string
        tools:
          type: array
          items:
            type: string
        version:
          type: string
        limits:
          type: object
          properties:
            maxReqPerHour:
              type: integer
            maxInputMB:
              type: integer
        pricing:
          type: object
          properties:
            perRunCents:
              type: integer
            perMBcents:
              type: integer
