# syntax=docker/dockerfile:1.7
FROM node:20-bookworm AS base

ENV PNPM_HOME="/pnpm"
ENV PNPM_STORE_DIR="/app/.pnpm-store"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN apt-get update && apt-get install -y \
  libc6 libstdc++6 libatomic1 libssl-dev \
  python3 make g++ git curl \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 1. Cache compartilhado
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY packages ./packages
RUN pnpm install

# 2. Código do serviço
COPY apps/cli ./apps/cli

CMD ["pnpm", "-C", "apps/cli", "dev"]
